# This is a basic workflow to help you get started with Actions

name: Braid

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Setup Rust to use nightly tool chain
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # Runs a single command using the runners shell
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1.2.0
        with:
          platform: linux
          
      - name: Setup gcc
        uses: egor-tensin/setup-gcc@v1

      # Runs a set of commands using the runners shell
      - name: Run Braid Test Suite
        run: |
          sudo ln -s bash /bin/sh.bash && mv /bin/sh.bash /bin/sh
          cd test
          ./test.sh
