# This is a basic workflow to help you get started with Actions

name: Bramble

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install LLVM 13
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 11
          sudo apt-get install llvm-11
          sudo apt-get install llvm-11-dev
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Rust to use nightly tool chain
      - name: rust-toolchain
        uses: actions-rs/toolchain@v1

      # Runs a set of commands using the runners shell
      - name: Run Bramble Test Suite
        run: |
          cd test
          bash ./test.sh
          bash ./test-imports.sh
          bash ./test-syntax.sh 5
